// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tailgrab.Models;

#nullable disable

namespace tailgrab.Migrations
{
    [DbContext(typeof(TailgrabDBContext))]
    [Migration("20260206180413_V1.0.10")]
    partial class V1010
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Tailgrab.Models.AvatarInfo", b =>
                {
                    b.Property<string>("AvatarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBOS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AvatarId");

                    b.ToTable("AvatarInfo", (string)null);
                });

            modelBuilder.Entity("Tailgrab.Models.GroupInfo", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createDate");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBOS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updateDate");

                    b.HasKey("GroupId");

                    b.ToTable("GroupInfo", (string)null);
                });

            modelBuilder.Entity("Tailgrab.Models.ImageEvaluation", b =>
                {
                    b.Property<string>("InventoryId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Evaluation")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("LastDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Md5checksum")
                        .HasColumnType("TEXT")
                        .HasColumnName("MD5Checksum");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryId");

                    b.ToTable("ImageEvaluation", (string)null);
                });

            modelBuilder.Entity("Tailgrab.Models.ProfileEvaluation", b =>
                {
                    b.Property<string>("Md5checksum")
                        .HasColumnType("TEXT")
                        .HasColumnName("MD5Checksum");

                    b.Property<byte[]>("Evaluation")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("LastDateTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfileText")
                        .HasColumnType("BLOB");

                    b.HasKey("Md5checksum");

                    b.ToTable("ProfileEvaluation", (string)null);
                });

            modelBuilder.Entity("Tailgrab.Models.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<double>("ElapsedMinutes")
                        .HasColumnType("REAL")
                        .HasColumnName("elapsedHours");

                    b.Property<int>("IsBos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBOS");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
