// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Tailgrab.Common;

namespace Tailgrab.Models;

public partial class AvatarInfo
{
    public string AvatarId { get; set; }

    public string UserId { get; set; }

    public string AvatarName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsBos { get; set; }

    public AlertTypeEnum AlertType { get; set; } = AlertTypeEnum.None;

    public string ImageUrl { get; set; }

    public AvatarInfo()
    {
        CreatedAt = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"GroupId: {AvatarId}, UserId: {UserId}, GroupName: {AvatarName}, CreatedAt: {CreatedAt}, UpdatedAt: {UpdatedAt}, IsBOS: {IsBos}, AlertType: {AlertType}";
    }
}