// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http.HttpResults;
using System;
using System.Collections.Generic;
using Tailgrab.Common;
using VRChat.API.Model;

namespace Tailgrab.Models;

public partial class GroupInfo
{
    public string GroupId { get; set; }

    public string GroupName{ get; set; }

    public bool IsBos{ get; set; }

    public AlertTypeEnum AlertType { get; set; } = AlertTypeEnum.None;

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public GroupInfo()
    {
        UpdatedAt = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"GroupId: {GroupId}, GroupName: {GroupName}, IsBOS: {IsBos}, AlertType: {AlertType}, CreatedAt: {CreatedAt}, UpdatedAt: {UpdatedAt}";
    }
}
