// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http.HttpResults;
using System;
using System.Collections.Generic;

namespace Tailgrab.Models;

public partial class ImageEvaluation
{
    public string InventoryId { get; set; }
    public string UserId { get; set; }
    public string Md5checksum { get; set; }
    public byte[] Evaluation { get; set; }
    public DateTime LastDateTime { get; set; }

    public ImageEvaluation()
    {
        LastDateTime = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"InventoryId: {InventoryId}, UserId: {UserId}, Md5checksum: {Md5checksum}, Evaluation: {BitConverter.ToString(Evaluation)}, LastDateTime: {LastDateTime}";
    }
}