// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http.HttpResults;
using System;
using System.Collections.Generic;
using VRChat.API.Model;

namespace Tailgrab.Models;

public partial class ModerationInfo
{
    public string Id { get; set; }

    public string ContentType { get; set; }

    public string ContentId { get; set; }

    public string ContentName { get; set; }

    public string UserId { get; set; }

    public string Thumbnail { get; set; }

    public byte[] Report { get; set; }

    public DateTime EventDateTime { get; set; }


    public ModerationInfo()
    {
        EventDateTime = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"ModerationInfo: Id={Id}, ContentId={ContentId}, ContentName={ContentName}, ContentType={ContentType}, UserId={UserId}, EventDateTime={EventDateTime}"; 
    }
}

