// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http.HttpResults;
using System;
using System.Collections.Generic;
using VRChat.API.Model;

namespace Tailgrab.Models;

public partial class ProfileEvaluation
{
    public string Md5checksum { get; set; }

    public byte[] ProfileText { get; set; }

    public byte[] Evaluation { get; set; }

    public DateTime LastDateTime { get; set; }

    public ProfileEvaluation()
    {
        LastDateTime = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"ProfileEvaluation: {Md5checksum}, ProfileText: {ProfileText}, Evaluation: {Evaluation}, LastDateTime: {LastDateTime}";
    }
}