// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Options;
using NLog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace Tailgrab.Models;


public class TailgrabContextFactory : IDesignTimeDbContextFactory<TailgrabDBContext>
{
    public TailgrabDBContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<TailgrabDBContext>();
        optionsBuilder.UseSqlite("Data Source=./Resources/tailgrab-dev.sqlite");

        return new TailgrabDBContext(optionsBuilder.Options);
    }
}

public partial class TailgrabDBContext : DbContext
{

    Logger logger = LogManager.GetCurrentClassLogger();

    public TailgrabDBContext(DbContextOptions<TailgrabDBContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=./data/avatars.sqlite");
    }

    public virtual DbSet<AvatarInfo> AvatarInfos { get; set; }

    public virtual DbSet<GroupInfo> GroupInfos { get; set; }

    public virtual DbSet<ProfileEvaluation> ProfileEvaluations { get; set; }

    public virtual DbSet<ImageEvaluation> ImageEvaluations { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AvatarInfo>(entity =>
        {
            entity.HasKey(e => e.AvatarId);

            entity.ToTable("AvatarInfo");

            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
        });

        modelBuilder.Entity<GroupInfo>(entity =>
        {
            entity.HasKey(e => e.GroupId);

            entity.ToTable("GroupInfo");

            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
            entity.Property(e => e.CreatedAt).HasColumnName("createDate");
            entity.Property(e => e.UpdatedAt).HasColumnName("updateDate");
        });

        modelBuilder.Entity<ProfileEvaluation>(entity =>
        {
            entity.HasKey(e => e.Md5checksum);

            entity.ToTable("ProfileEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserInfo");

            entity.Property(e => e.CreatedAt).IsRequired();
            entity.Property(e => e.ElapsedMinutes).HasColumnName("elapsedHours");
            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
        });

        modelBuilder.Entity<ImageEvaluation>(entity =>
        {
            entity.HasKey(e => e.InventoryId);

            entity.ToTable("ImageEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    public void UpgradeDatabase()
    {
        ExecuteSqlTransaction(
            "ALTER TABLE AvatarInfo ADD COLUMN alertType INTEGER NOT NULL DEFAULT 0",
            "UPDATE AvatarInfo SET alertType = 1 WHERE IsBOS = 1",
            "ALTER TABLE GroupInfo ADD COLUMN alertType INTEGER NOT NULL DEFAULT 0",
            "UPDATE GroupInfo SET alertType = 1 WHERE IsBOS = 1"
        );
    }

    private void ExecuteSql(string sql)
    {
        Database.ExecuteSqlRaw(sql);
    }

    private void ExecuteSqlTransaction(params string[] sqlStatements)
    {
        using var transaction = Database.BeginTransaction();
        try
        {
            foreach (var sql in sqlStatements)
            {
                Database.ExecuteSqlRaw(sql);
            }
            transaction.Commit();
        }
        catch
        {
            transaction.Rollback();
            throw;
        }
    }

    private async Task ExecuteSqlAsync(string sql)
    {
        await Database.ExecuteSqlRawAsync(sql);
    }

    private async Task ExecuteSqlTransactionAsync(params string[] sqlStatements)
    {
        using var transaction = await Database.BeginTransactionAsync();
        try
        {
            foreach (var sql in sqlStatements)
            {
                await Database.ExecuteSqlRawAsync(sql);
            }
            await transaction.CommitAsync();
        }
        catch
        {
            await transaction.RollbackAsync();
            throw;
        }
    }
    public void CreateDatabaseBackup()
    {
        try
        {
            var dataDir = Path.Combine(AppContext.BaseDirectory, "data");
            var databasePath = Path.Combine(dataDir, "avatars.sqlite");

            if (!File.Exists(databasePath))
            {
                logger.Warn($"Database file not found at '{databasePath}'. Nothing to backup.");
                return;
            }

            // Create backup directory with timestamp
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var backupDirName = $"backup_{timestamp}";
            var backupDir = Path.Combine(dataDir, backupDirName);
            Directory.CreateDirectory(backupDir);

            logger.Info($"Creating database backup in: '{backupDirName}'");

            // Export each table to JSON
            int totalRecords = 0;

            // Export AvatarInfo table
            logger.Info("Exporting AvatarInfo table...");
            var avatars = AvatarInfos.ToList();
            var avatarsJson = JsonSerializer.Serialize(avatars, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "AvatarInfo.json"), avatarsJson);
            logger.Info($"  Exported {avatars.Count} avatar records");
            totalRecords += avatars.Count;

            // Export GroupInfo table
            logger.Info("Exporting GroupInfo table...");
            var groups = GroupInfos.ToList();
            var groupsJson = JsonSerializer.Serialize(groups, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "GroupInfo.json"), groupsJson);
            logger.Info($"  Exported {groups.Count} group records");
            totalRecords += groups.Count;

            // Export UserInfo table
            logger.Info("Exporting UserInfo table...");
            var users = UserInfos.ToList();
            var usersJson = JsonSerializer.Serialize(users, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "UserInfo.json"), usersJson);
            logger.Info($"  Exported {users.Count} user records");
            totalRecords += users.Count;

            // Export ProfileEvaluation table
            logger.Info("Exporting ProfileEvaluation table...");
            var profiles = ProfileEvaluations.ToList();
            var profilesJson = JsonSerializer.Serialize(profiles, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "ProfileEvaluation.json"), profilesJson);
            logger.Info($"  Exported {profiles.Count} profile evaluation records");
            totalRecords += profiles.Count;

            // Export ImageEvaluation table
            logger.Info("Exporting ImageEvaluation table...");
            var images = ImageEvaluations.ToList();
            var imagesJson = JsonSerializer.Serialize(images, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "ImageEvaluation.json"), imagesJson);
            logger.Info($"  Exported {images.Count} image evaluation records");
            totalRecords += images.Count;

            // Create backup metadata file
            var metadata = new
            {
                BackupTimestamp = timestamp,
                BackupDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                ApplicationVersion = BuildInfo.GetInformationalVersion(),
                DatabasePath = databasePath,
                TotalRecords = totalRecords,
                Tables = new[]
                {
                    new { TableName = "AvatarInfo", RecordCount = avatars.Count },
                    new { TableName = "GroupInfo", RecordCount = groups.Count },
                    new { TableName = "UserInfo", RecordCount = users.Count },
                    new { TableName = "ProfileEvaluation", RecordCount = profiles.Count },
                    new { TableName = "ImageEvaluation", RecordCount = images.Count }
                }
            };
            var metadataJson = JsonSerializer.Serialize(metadata, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "_backup_metadata.json"), metadataJson);

            // Calculate total backup size
            var backupDirInfo = new DirectoryInfo(backupDir);
            var totalSize = backupDirInfo.GetFiles().Sum(f => f.Length);

            logger.Info($"Database backup completed successfully:");
            logger.Info($"  Location: '{backupDir}'");
            logger.Info($"  Total records: {totalRecords}");
            logger.Info($"  Backup size: {totalSize / 1024.0:F2} KB");

            // Clean up old backups (keep only last 10)
            CleanupOldBackups(dataDir, 10);
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Failed to create database backup");
        }
    }

    /// <summary>
    /// Clean up old backup directories, keeping only the specified number of most recent backups.
    /// </summary>
    private void CleanupOldBackups(string dataDir, int keepCount)
    {
        try
        {
            var backupDirs = Directory.GetDirectories(dataDir, "backup_*")
                .Select(d => new DirectoryInfo(d))
                .OrderByDescending(d => d.CreationTime)
                .ToList();

            if (backupDirs.Count > keepCount)
            {
                var dirsToDelete = backupDirs.Skip(keepCount);
                foreach (var dir in dirsToDelete)
                {
                    logger.Info($"Deleting old backup directory: '{dir.Name}'");
                    dir.Delete(recursive: true);
                }
            }
        }
        catch (Exception ex)
        {
            logger.Warn(ex, "Failed to clean up old backup directories");
        }
    }
}
