// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Options;
using NLog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Windows.Media.Animation;
using tailgrab.src.Models;
using Tailgrab.Common;

namespace Tailgrab.Models;


public class TailgrabContextFactory : IDesignTimeDbContextFactory<TailgrabDBContext>
{
    public TailgrabDBContext CreateDbContext(string[] args)
    {
        // Define directory: %LOCALAPPDATA%\YourAppName
        string dbFolder = Path.Combine(CommonConst.APPLICATION_LOCAL_DATA_PATH, "data");
        string dbPath = Path.Combine(dbFolder, CommonConst.APPLICATION_LOCAL_DATABASE);

        var optionsBuilder = new DbContextOptionsBuilder<TailgrabDBContext>();
        optionsBuilder.UseSqlite($"Data Source={dbPath}");

        return new TailgrabDBContext(optionsBuilder.Options);
    }
}

public partial class TailgrabDBContext : DbContext
{

    Logger logger = LogManager.GetCurrentClassLogger();

    public TailgrabDBContext(DbContextOptions<TailgrabDBContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Define directory: %LOCALAPPDATA%\YourAppName
        string dbFolder = Path.Combine(CommonConst.APPLICATION_LOCAL_DATA_PATH, "data");
        string dbPath = Path.Combine(dbFolder, CommonConst.APPLICATION_LOCAL_DATABASE);

        // Ensure directory exists
        Directory.CreateDirectory(dbFolder);

        // Configure SQLite
        optionsBuilder.UseSqlite($"Data Source={dbPath}");
    }

    public virtual DbSet<AvatarInfo> AvatarInfos { get; set; }

    public virtual DbSet<GroupInfo> GroupInfos { get; set; }

    public virtual DbSet<GroupManagement> GroupManagements { get; set; }

    public virtual DbSet<ProfileEvaluation> ProfileEvaluations { get; set; }

    public virtual DbSet<ImageEvaluation> ImageEvaluations { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AvatarInfo>(entity =>
        {
            entity.HasKey(e => e.AvatarId);

            entity.ToTable("AvatarInfo");

            entity.HasIndex(a => a.AvatarName);
            entity.HasIndex(a => a.UserName);
            entity.HasIndex(a => a.AlertType);
        });

        modelBuilder.Entity<GroupInfo>(entity =>
        {
            entity.HasKey(e => e.GroupId);

            entity.ToTable("GroupInfo");

            entity.Property(e => e.CreatedAt).HasColumnName("createDate");
            entity.Property(e => e.UpdatedAt).HasColumnName("updateDate");

            entity.HasIndex(g => g.GroupName);
            entity.HasIndex(g => g.AlertType);
        });

        modelBuilder.Entity<GroupManagement>(entity =>
        {
            entity.HasKey(e => e.GroupId);

            entity.ToTable("GroupManagement");

            entity.Property(e => e.CreatedAt).HasColumnName("createDate");
            entity.Property(e => e.UpdatedAt).HasColumnName("updateDate");

            entity.HasIndex(g => g.GroupName);
        });

        modelBuilder.Entity<ProfileEvaluation>(entity =>
        {
            entity.HasKey(e => e.Md5checksum);

            entity.ToTable("ProfileEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
            entity.Property(e => e.IsIgnored).HasColumnName("isIgnored");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserInfo");

            entity.Property(e => e.CreatedAt).IsRequired();
        });

        modelBuilder.Entity<ImageEvaluation>(entity =>
        {
            entity.HasKey(e => e.InventoryId);

            entity.ToTable("ImageEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
            entity.Property(e => e.IsIgnored).HasColumnName("isIgnored");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    public void UpgradeDatabase()
    {
        ExecuteSqlTransaction(
            "CREATE INDEX IF NOT EXISTS ix_avtr_aname ON AvatarInfo(AvatarName)",
            "CREATE INDEX IF NOT EXISTS ix_avtr_uname ON AvatarInfo(UserName)",
            "CREATE INDEX IF NOT EXISTS ix_avtr_alert ON AvatarInfo(alertType)",
            "CREATE INDEX IF NOT EXISTS ix_grp_gname ON GroupInfo(groupName)",
            "CREATE INDEX IF NOT EXISTS ix_grp_alert ON GroupInfo(alertType)",
            "CREATE TABLE IF NOT EXISTS GroupManagement ( GroupId TEXT NOT NULL CONSTRAINT PK_GroupManagement PRIMARY KEY, GroupName TEXT NULL, createDate TEXT NOT NULL, updateDate TEXT NULL )",
            "CREATE INDEX IF NOT EXISTS ix_grpm_gname ON GroupManagement(groupName)"
        );
    }

    private void ExecuteSql(string sql)
    {
        Database.ExecuteSqlRaw(sql);
    }

    private void ExecuteSqlTransaction(params string[] sqlStatements)
    {
        using var transaction = Database.BeginTransaction();
        foreach (var sql in sqlStatements)
        {
            try
            {
                logger.Warn(sql);
                Database.ExecuteSqlRaw(sql);
            }
            catch
            {
                logger.Error($"Error executing SQL transaction. Rolling back changes. {sql}");
                transaction.Rollback();
                throw;
            }
        }
        transaction.Commit();
    }

    private async Task ExecuteSqlAsync(string sql)
    {
        await Database.ExecuteSqlRawAsync(sql);
    }

    private async Task ExecuteSqlTransactionAsync(params string[] sqlStatements)
    {
        using var transaction = await Database.BeginTransactionAsync();
        try
        {
            foreach (var sql in sqlStatements)
            {
                await Database.ExecuteSqlRawAsync(sql);
            }
            await transaction.CommitAsync();
        }
        catch
        {
            await transaction.RollbackAsync();
            throw;
        }
    }
    public void CreateDatabaseBackup()
    {
        try
        {
            var dataDir = Path.Combine(AppContext.BaseDirectory, "data");
            var databasePath = Path.Combine(dataDir, "avatars.sqlite");

            if (!File.Exists(databasePath))
            {
                logger.Warn($"Database file not found at '{databasePath}'. Nothing to backup.");
                return;
            }

            // Create backup directory with timestamp
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var backupDirName = $"backup_{timestamp}";
            var backupDir = Path.Combine(dataDir, backupDirName);
            Directory.CreateDirectory(backupDir);

            logger.Info($"Creating database backup in: '{backupDirName}'");

            // Export each table to JSON
            int totalRecords = 0;

            // Export AvatarInfo table
            logger.Info("Exporting AvatarInfo table...");
            var avatars = AvatarInfos.ToList();
            var avatarsJson = JsonSerializer.Serialize(avatars, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "AvatarInfo.json"), avatarsJson);
            logger.Info($"  Exported {avatars.Count} avatar records");
            totalRecords += avatars.Count;

            // Export GroupInfo table
            logger.Info("Exporting GroupInfo table...");
            var groups = GroupInfos.ToList();
            var groupsJson = JsonSerializer.Serialize(groups, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "GroupInfo.json"), groupsJson);
            logger.Info($"  Exported {groups.Count} group records");
            totalRecords += groups.Count;

            // Export UserInfo table
            logger.Info("Exporting UserInfo table...");
            var users = UserInfos.ToList();
            var usersJson = JsonSerializer.Serialize(users, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "UserInfo.json"), usersJson);
            logger.Info($"  Exported {users.Count} user records");
            totalRecords += users.Count;

            // Export ProfileEvaluation table
            logger.Info("Exporting ProfileEvaluation table...");
            var profiles = ProfileEvaluations.ToList();
            var profilesJson = JsonSerializer.Serialize(profiles, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "ProfileEvaluation.json"), profilesJson);
            logger.Info($"  Exported {profiles.Count} profile evaluation records");
            totalRecords += profiles.Count;

            // Export ImageEvaluation table
            logger.Info("Exporting ImageEvaluation table...");
            var images = ImageEvaluations.ToList();
            var imagesJson = JsonSerializer.Serialize(images, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "ImageEvaluation.json"), imagesJson);
            logger.Info($"  Exported {images.Count} image evaluation records");
            totalRecords += images.Count;

            // Create backup metadata file
            var metadata = new
            {
                BackupTimestamp = timestamp,
                BackupDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                ApplicationVersion = BuildInfo.GetInformationalVersion(),
                DatabasePath = databasePath,
                TotalRecords = totalRecords,
                Tables = new[]
                {
                    new { TableName = "AvatarInfo", RecordCount = avatars.Count },
                    new { TableName = "GroupInfo", RecordCount = groups.Count },
                    new { TableName = "UserInfo", RecordCount = users.Count },
                    new { TableName = "ProfileEvaluation", RecordCount = profiles.Count },
                    new { TableName = "ImageEvaluation", RecordCount = images.Count }
                }
            };
            var metadataJson = JsonSerializer.Serialize(metadata, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(Path.Combine(backupDir, "_backup_metadata.json"), metadataJson);

            // Calculate total backup size
            var backupDirInfo = new DirectoryInfo(backupDir);
            var totalSize = backupDirInfo.GetFiles().Sum(f => f.Length);

            logger.Info($"Database backup completed successfully:");
            logger.Info($"  Location: '{backupDir}'");
            logger.Info($"  Total records: {totalRecords}");
            logger.Info($"  Backup size: {totalSize / 1024.0:F2} KB");

            // Clean up old backups (keep only last 10)
            CleanupOldBackups(dataDir, 10);
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Failed to create database backup");
        }
    }

    /// <summary>
    /// Clean up old backup directories, keeping only the specified number of most recent backups.
    /// </summary>
    private void CleanupOldBackups(string dataDir, int keepCount)
    {
        try
        {
            var backupDirs = Directory.GetDirectories(dataDir, "backup_*")
                .Select(d => new DirectoryInfo(d))
                .OrderByDescending(d => d.CreationTime)
                .ToList();

            if (backupDirs.Count > keepCount)
            {
                var dirsToDelete = backupDirs.Skip(keepCount);
                foreach (var dir in dirsToDelete)
                {
                    logger.Info($"Deleting old backup directory: '{dir.Name}'");
                    dir.Delete(recursive: true);
                }
            }
        }
        catch (Exception ex)
        {
            logger.Warn(ex, "Failed to clean up old backup directories");
        }
    }

    public MigrationStatus MigrateOldVersion(string dataDir)
    {
        MigrationStatus status = new MigrationStatus();
        List<string> migrationTables = new List<string>()
        {
            "AvatarInfo",
            "GroupInfo",
            "UserInfo",
            "ProfileEvaluation",
            "ImageEvaluation"
        };

        foreach (var table in migrationTables)
        {
            int count = GetTableCount(dataDir, table);
            status.Messages.Add($"Table '{table}' has {count} records."); 
            logger.Info($"Table '{table}' has {count} records.");

            int migratedCount = MigrateTable(dataDir, table);
            status.Messages.Add($"Migrated {migratedCount} records from '{table}' to new database.");
            logger.Info($"Migrated {migratedCount} records from '{table}' to new database.");
        }

        return status;
    }

    public int MigrateTable(string dataDir, string tableName)
    {
        switch (tableName)
        {
            case "GroupInfo":
                return MigrateGroupInfo(dataDir);
            case "UserInfo":
                return MigrateUserInfo(dataDir);
            case "ProfileEvaluation":                
                return MigrateProfileEvaluation(dataDir);
            case "ImageEvaluation":
                return MigrateImageEvaluation(dataDir);
            case "AvatarInfo":
                return MigrateAvatarInfo(dataDir);
            default:
                logger.Warn($"No migration logic defined for table '{tableName}'. Skipping.");
                return 0;
        }
    }

    private Int32 GetTableCount(string dataDir, string tableName)
    {
        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT Count() FROM {tableName}";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            return Convert.ToInt32(command.ExecuteScalar());
        }
        catch (Exception ex)
        {
            logger.Error(ex, $"Error reading {tableName} data for record count");
            return 0;
        }

    }

    private Int32 MigrateAvatarInfo(string dataDir)
    {
        int count = 0;
        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT AvatarId, UserId, AvatarName, CreatedAt, UpdatedAt, IsBOS, ImageUrl FROM AvatarInfo";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                string avatarId = reader.GetString(0);
                string userId = reader.GetString(1);
                string avatarName = reader.GetString(2);
                string createdAt = reader.GetString(3);
                string updatedAt = reader.GetString(4);
                bool isBOS = reader.GetBoolean(5);
                string imageUrl = reader.GetString(6);

                AvatarInfo? existing = AvatarInfos.Find(avatarId);
                if (existing == null && !string.IsNullOrEmpty(userId))
                {
                    AvatarInfo avatarInfo = new AvatarInfo();
                    avatarInfo.AvatarId = avatarId;
                    avatarInfo.UserId = userId;
                    avatarInfo.AvatarName = avatarName;
                    avatarInfo.CreatedAt = DateTime.Parse(createdAt);
                    avatarInfo.UpdatedAt = DateTime.Parse(updatedAt);
                    avatarInfo.AlertType = isBOS ? AlertTypeEnum.Watch : AlertTypeEnum.None;
                    avatarInfo.ImageUrl = imageUrl;

                    this.Add(avatarInfo);
                    count++;
                }
            }
            this.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Error reading AvatarInfo data for migration");
            return count;
        }

        return count;
    }

    private Int32 MigrateGroupInfo(string dataDir)
    {
        int count = 0;

        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT groupId, groupName, createDate, updateDate, IsBOS FROM GroupInfo";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                string groupId = reader.GetString(0);
                string groupName = reader.GetString(1);
                string createdAt = reader.GetString(2);
                string updatedAt = reader.GetString(3);
                bool isBOS = reader.GetBoolean(4);

                GroupInfo? existing = GroupInfos.Find(groupId);
                if (existing == null)
                {
                    GroupInfo groupInfo = new GroupInfo();
                    groupInfo.GroupId = groupId;
                    groupInfo.GroupName = groupName;
                    groupInfo.CreatedAt = DateTime.Parse(createdAt);
                    groupInfo.UpdatedAt = DateTime.Parse(updatedAt);
                    groupInfo.AlertType = isBOS ? AlertTypeEnum.Watch : AlertTypeEnum.None;

                    this.Add(groupInfo);
                    count++;
                }
            }
            this.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Error reading GroupInfo data for migration");
            return count;
        }

        return count;
    }

    private Int32 MigrateUserInfo(string dataDir)
    {
        int count = 0;
        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT UserId, DisplayName, elapsedHours, CreatedAt, UpdatedAt, IsBOS FROM UserInfo";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                string userId = reader.GetString(0);
                string displayName = reader.GetString(1);
                float elapsedHours = reader.GetFloat(2);
                string createdAt = reader.GetString(3);
                string updatedAt = reader.GetString(4);
                bool isBOS = reader.GetBoolean(5);

                UserInfo? existing = UserInfos.Find(userId);
                if (existing == null)
                {
                    UserInfo userInfo = new UserInfo();
                    userInfo.UserId = userId;
                    userInfo.DisplayName = displayName;
                    userInfo.ElapsedMinutes = elapsedHours;
                    userInfo.CreatedAt = DateTime.Parse(createdAt);
                    userInfo.UpdatedAt = DateTime.Parse(updatedAt);
                    //userInfo.AlertType = isBOS ? AlertTypeEnum.Watch : AlertTypeEnum.None;

                    this.Add(userInfo);
                    count++;
                }
            }
            this.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Error reading UserInfo data for migration");
            return count;
        }

        return count;
    }

    private Int32 MigrateProfileEvaluation(string dataDir)
    {
        int count = 0;
        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT MD5Checksum, ProfileText, Evaluation, LastDateTime FROM ProfileEvaluation";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                string md5Checksum = reader.GetString(0);
                string profileText = reader.GetString(1);
                string evaluation = reader.GetString(2);
                string lastDateTime = reader.GetString(3);

                ProfileEvaluation? existing = ProfileEvaluations.Find(md5Checksum);
                if (existing == null)
                {
                    ProfileEvaluation profileEval = new ProfileEvaluation();
                    profileEval.Md5checksum = md5Checksum;
                    profileEval.ProfileText = System.Text.Encoding.UTF8.GetBytes(profileText);
                    profileEval.Evaluation = System.Text.Encoding.UTF8.GetBytes(evaluation);
                    profileEval.LastDateTime  = DateTime.Parse(lastDateTime);
                    //profileEval.AlertType = isBOS ? AlertTypeEnum.Watch : AlertTypeEnum.None;

                    this.Add(profileEval);
                    count++;
                }
            }
            this.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Error reading UserInfo data for migration");
            return count;
        }

        return count;
    }

    private Int32 MigrateImageEvaluation(string dataDir)
    {
        int count = 0;
        string connectionString = $"Data Source={Path.Combine(AppContext.BaseDirectory, "data", "avatars.sqlite")}";
        string query = $"SELECT InventoryId, MD5Checksum, Evaluation, LastDateTime, UserId FROM ImageEvaluation";
        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = new SqliteCommand(query, connection);

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                string inventoryId = reader.GetString(0);
                string md5Checksum = reader.GetString(1);
                string evaluation = reader.GetString(2);
                string lastDateTime = reader.GetString(3);
                string userId = reader.GetString(4);

                ImageEvaluation? existing = ImageEvaluations.Find(inventoryId);
                if (existing == null)
                {
                    ImageEvaluation imageEval = new ImageEvaluation();
                    imageEval.InventoryId = inventoryId;
                    imageEval.Md5checksum = md5Checksum;
                    imageEval.Evaluation = System.Text.Encoding.UTF8.GetBytes(evaluation);
                    imageEval.LastDateTime = DateTime.Parse(lastDateTime);
                    imageEval.UserId = userId;
                    //imageEval.AlertType = isBOS ? AlertTypeEnum.Watch : AlertTypeEnum.None;

                    this.Add(imageEval);
                    count++;
                }
            }
            this.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Error reading UserInfo data for migration");
            return count;
        }

        return count;
    }
}


public class MigrationStatus
{
    public List<string> Messages { get; set; } = new List<string>();    
}