// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;

namespace Tailgrab.Models;


public class TailgrabContextFactory : IDesignTimeDbContextFactory<TailgrabDBContext>
{
    public TailgrabDBContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<TailgrabDBContext>();
        optionsBuilder.UseSqlite("Data Source=./Resources/tailgrab-dev.sqlite");

        return new TailgrabDBContext(optionsBuilder.Options);
    }
}

public partial class TailgrabDBContext : DbContext
{
    public TailgrabDBContext(DbContextOptions<TailgrabDBContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=./data/avatars.sqlite");
    }

    public virtual DbSet<AvatarInfo> AvatarInfos { get; set; }

    public virtual DbSet<GroupInfo> GroupInfos { get; set; }

    public virtual DbSet<ProfileEvaluation> ProfileEvaluations { get; set; }

    public virtual DbSet<ImageEvaluation> ImageEvaluations { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AvatarInfo>(entity =>
        {
            entity.HasKey(e => e.AvatarId);

            entity.ToTable("AvatarInfo");

            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
        });

        modelBuilder.Entity<GroupInfo>(entity =>
        {
            entity.HasKey(e => e.GroupId);

            entity.ToTable("GroupInfo");

            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
            entity.Property(e => e.CreatedAt).HasColumnName("createDate");
            entity.Property(e => e.UpdatedAt).HasColumnName("updateDate");
        });

        modelBuilder.Entity<ProfileEvaluation>(entity =>
        {
            entity.HasKey(e => e.Md5checksum);

            entity.ToTable("ProfileEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserInfo");

            entity.Property(e => e.CreatedAt).IsRequired();
            entity.Property(e => e.ElapsedMinutes).HasColumnName("elapsedHours");
            entity.Property(e => e.IsBos).HasColumnName("IsBOS");
        });

        modelBuilder.Entity<ImageEvaluation>(entity =>
        {
            entity.HasKey(e => e.InventoryId);

            entity.ToTable("ImageEvaluation");

            entity.Property(e => e.Md5checksum).HasColumnName("MD5Checksum");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    public void UpgradeDatabase()
    {
        ExecuteSqlTransaction(
            "ALTER TABLE AvatarInfo ADD COLUMN alertType INTEGER NOT NULL DEFAULT 0",
            "UPDATE AvatarInfo SET alertType = 1 WHERE IsBOS = 1",
            "ALTER TABLE GroupInfo ADD COLUMN alertType INTEGER NOT NULL DEFAULT 0",
            "UPDATE GroupInfo SET alertType = 1 WHERE IsBOS = 1"
        );
    }

    private void ExecuteSql(string sql)
    {
        Database.ExecuteSqlRaw(sql);
    }

    private void ExecuteSqlTransaction(params string[] sqlStatements)
    {
        using var transaction = Database.BeginTransaction();
        try
        {
            foreach (var sql in sqlStatements)
            {
                Database.ExecuteSqlRaw(sql);
            }
            transaction.Commit();
        }
        catch
        {
            transaction.Rollback();
            throw;
        }
    }

    private async Task ExecuteSqlAsync(string sql)
    {
        await Database.ExecuteSqlRawAsync(sql);
    }

    private async Task ExecuteSqlTransactionAsync(params string[] sqlStatements)
    {
        using var transaction = await Database.BeginTransactionAsync();
        try
        {
            foreach (var sql in sqlStatements)
            {
                await Database.ExecuteSqlRawAsync(sql);
            }
            await transaction.CommitAsync();
        }
        catch
        {
            await transaction.RollbackAsync();
            throw;
        }
    }
}