// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailgrab.Models;

public partial class UserInfo
{
    public string UserId { get; set; }

    public string DisplayName { get; set; }

    public double ElapsedMinutes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateOnly DateJoined { get; set; }

    public string LastProfileChecksum { get; set; }

    public UserInfo()
    {
        CreatedAt = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"UserInfo: UserId={UserId}, DisplayName={DisplayName}, ElapsedMinutes={ElapsedMinutes}, CreatedAt={CreatedAt}, UpdatedAt={UpdatedAt}, DateJoined={DateJoined}, LastProfileChecksum={LastProfileChecksum}";
    }
}