// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using VRChat.API.Model;

namespace Tailgrab.Models;

public partial class UserInfo
{
    public string UserId { get; set; }

    public string DisplayName { get; set; }

    public double ElapsedMinutes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int IsBos { get; set; }
    public UserInfo()
    {
        CreatedAt = DateTime.UtcNow;
    }

    public override string ToString()
    {
        return $"UserInfo: {UserId}, DisplayName: {DisplayName}, ElapsedMinutes: {ElapsedMinutes}, CreatedAt: {CreatedAt}, UpdatedAt: {UpdatedAt}";
    }
}